#!/bin/sh

LCROND=/bin/usr/lcrond
LCROND_OPTS="-v" # -c /ect/lcron.conf

start() {
	$LCROND $LCROND_OPTS
	return $?
}

stop() {
	killall $LCROND
	return $?
}

case $1 in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop && start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
esac
